config/routes.rb
XFactorPredictor::Application.routes.draw do
  resources :metrics

  get "contest/index"

  get "contest/new"

  get "contest/show"

  get "contest/create"

  get "contest/edit"

  get "contest/update"

  get "contest/destroy"

  resources :keywords

  resources :scores

  resources :contestants do
    resources :search_terms
  end
  
  match "get_scores/:id" => "scores#generate_scores"

  get "home/index"
  
  resources :contests
  
  match "schedule_job" => "application#schedule_job_for_12_hours"
  
  match "schedule_job_24" => "application#schedule_job_for_24_hours"
  
  match "debug" => "application#debug"
  
  match "get_leaders" => "webservice#get_leaders"
  
  match "get_leaders_legally" => "webservice#get_leaders_legally"
  
  match 'get_leaders_test' => "webservice#get_leaders_test"
  
  match 'news' => "webservice#record_news_retreival"
  
  match 'info' => "webservice#record_info_retreival"
  
  match 'twitter' => "webservice#record_twitter_retreival"
  
  match 'clear_scores' => "webservice#clear_scores"

  root :to => "home#index"

end

app/models/contestant.rb
class Contestant < ActiveRecord::Base
  has_many :search_terms, :dependent => :destroy
  has_many :scores, :dependent => :destroy
  
  validates :name, :presence => true
end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
  # GET /contestants
  # GET /contestants.xml
  def index
    @contestants = Contestant.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contestants }
    end
  end

  # GET /contestants/1
  # GET /contestants/1.xml
  def show
    @contestant = Contestant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @contestant }
    end
  end

  # GET /contestants/new
  # GET /contestants/new.xml
  def new
    @contestant = Contestant.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @contestant }
    end
  end

  # GET /contestants/1/edit
  def edit
    @contestant = Contestant.find(params[:id])
  end

  # POST /contestants
  # POST /contestants.xml
  def create
    @contestant = Contestant.new(params[:contestant])

    respond_to do |format|
      if @contestant.save
        term  = SearchTerm.new
        term.contestant = @contestant
        term.value = @contestant.name
        if term.save
          format.html { redirect_to(@contestant, :notice => 'Contestant was successfully created.') }
          format.xml  { render :xml => @contestant, :status => :created, :location => @contestant }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @contestant.errors, :status => :unprocessable_entity }
        end
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contestant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contestants/1
  # PUT /contestants/1.xml
  def update
    @contestant = Contestant.find(params[:id])

    respond_to do |format|
      if @contestant.update_attributes(params[:contestant])
        format.html { redirect_to(@contestant, :notice => 'Contestant was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @contestant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contestants/1
  # DELETE /contestants/1.xml
  def destroy
    @contestant = Contestant.find(params[:id])
    @contestant.destroy

    respond_to do |format|
      format.html { redirect_to(contestants_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/contestants_helper.rb
module ContestantsHelper
  
  def update_latest_score_for_contest(contestant, contest)
    
    Rails.logger.info("Updating new score for " + contestant.name)
    latest_score = Score.where("contestant_id = ? and contest_id = ?", contestant.id, contest.id).sum('value')
    Rails.logger.info("Latest score for " + contestant.name.to_s + " is " + latest_score.to_s)
    term_count = contestant.search_terms.size
    unless term_count.nil?
      contestant.latest_score = latest_score / term_count
    else
      contestant.latest_score = latest_score
    end
    contestant.save
    Rails.logger.info("Saving")
  end
  
  def reset_score_for_contest(contestant)
    
    Rails.logger.info("Resetting score for " + contestant.name)
    contestant.latest_score = 0
    contestant.save
    Rails.logger.info("Saving")
    
  end
  
end

app/views/contestants/_form.html.erb
<%= form_for(@contestant) do |f| %>
  <% if @contestant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contestant.errors.count, "error") %> prohibited this contestant from being saved:</h2>

      <ul>
      <% @contestant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
	<%= f.label :multiplier %> 
  	<select name="contestant[multiplier]">
		<option value="1">1</option>
		<option value="2">2</option>
		<option value="3">3</option>
		<option value="4">4</option>
		<option value="5">5</option>
		<option value="6">6</option>
		<option value="7">7</option>
		<option value="8">8</option>
		<option value="9">9</option>
		<option value="10">10</option>
		<option value="11">11</option>
		<option value="12">12</option>
		<option value="13">13</option>
		<option value="14">14</option>
		<option value="15">15</option>
		<option value="16">16</option>
	</select>
  </div>

  <div class="field">
	<%= f.label :eliminated %> 
  	<%= f.check_box :eliminated %>
  </div>
	
	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contestants/edit.html.erb
<h1>Editing contestant</h1>

<%= render 'form' %>

<%= link_to 'Show', @contestant %> |
<%= link_to 'Back', contestants_path %>

app/views/contestants/index.html.erb
<h1>Listing contestants</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contestants.each do |contestant| %>
  <tr>
    <td><%= contestant.name %></td>
    <td><%= link_to 'Show', contestant %></td>
    <td><%= link_to 'Edit', edit_contestant_path(contestant) %></td>
    <td><%= link_to 'Destroy', contestant, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contestant', new_contestant_path %>

app/views/contestants/new.html.erb
<h1>New contestant</h1>

<%= render 'form' %>

<%= link_to 'Back', contestants_path %>

app/views/contestants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @contestant.name %>
</p>

<p>
  <b>Search Termss:</b>
  <% @contestant.search_terms.each do |s| %>
	<%= s.value %>(<%= s.id %>) - <%= link_to 'delete', contestant_search_term_path(@contestant, s),:method => :delete, :confirm => "you sure?", :remote => true%><br/>
  <%end%>
</p>

<%= form_for([@contestant, @contestant.search_terms.build]) do |f| %>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Edit', edit_contestant_path(@contestant) %> |
<%= link_to 'Back', contestants_path %>