config/routes.rb
XFactorPredictor::Application.routes.draw do
  resources :metrics

  get "contest/index"

  get "contest/new"

  get "contest/show"

  get "contest/create"

  get "contest/edit"

  get "contest/update"

  get "contest/destroy"

  resources :keywords

  resources :scores

  resources :contestants do
    resources :search_terms
  end
  
  match "get_scores/:id" => "scores#generate_scores"

  get "home/index"
  
  resources :contests
  
  match "schedule_job" => "application#schedule_job_for_12_hours"
  
  match "schedule_job_24" => "application#schedule_job_for_24_hours"
  
  match "debug" => "application#debug"
  
  match "get_leaders" => "webservice#get_leaders"
  
  match "get_leaders_legally" => "webservice#get_leaders_legally"
  
  match 'get_leaders_test' => "webservice#get_leaders_test"
  
  match 'news' => "webservice#record_news_retreival"
  
  match 'info' => "webservice#record_info_retreival"
  
  match 'twitter' => "webservice#record_twitter_retreival"
  
  match 'clear_scores' => "webservice#clear_scores"

  root :to => "home#index"

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  has_many :scores, :dependent => :destroy
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  # GET /contests
  # GET /contests.xml
  def index
    @contests = Contest.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contests }
    end
  end

  # GET /contests/1
  # GET /contests/1.xml
  def show
    @contest = Contest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @contest }
    end
  end

  # GET /contests/new
  # GET /contests/new.xml
  def new
    @contest = Contest.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @contest }
    end
  end

  # GET /contests/1/edit
  def edit
    @contest = Contest.find(params[:id])
  end

  # POST /contests
  # POST /contests.xml
  def create
    @contest = Contest.new(params[:contest])

    respond_to do |format|
      if @contest.save
        format.html { redirect_to(@contest, :notice => 'Contest was successfully created.') }
        format.xml  { render :xml => @contest, :status => :created, :location => @contest }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contest.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contests/1
  # PUT /contests/1.xml
  def update
    @contest = Contest.find(params[:id])

    respond_to do |format|
      if @contest.update_attributes(params[:contest])
        format.html { redirect_to(@contest, :notice => 'Contest was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @contest.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.xml
  def destroy
    @contest = Contest.find(params[:id])
    @contest.destroy

    respond_to do |format|
      format.html { redirect_to(contests_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/contests_helper.rb
module ContestsHelper
  
  def is_contest_running
    
    require 'time'
    Rails.logger.info("Checking to see if contest is running")
    Rails.logger.info("Current time is: " + Time.now.to_s)
    
    contest = Contest.find(:first, :conditions => ["contest_start <= ? AND contest_end >= ?", Time.now, Time.now])
    
    unless contest.nil?
      Rails.logger.info("Contest with id " + contest.id.to_s + " found, returning.")
      return contest
    else
      Rails.logger.info("No contest found, returning.")
      return nil
    end
    
  end
  
end

app/views/contests/_form.html.erb
<%= form_for(@contest) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% @contest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contest_start %><br />
    <%= f.datetime_select :contest_start %>
  </div>
  <div class="field">
    <%= f.label :contest_end %><br />
    <%= f.datetime_select :contest_end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<h1>Editing contest</h1>

<%= render 'form' %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<h1>Listing contests</h1>

<table>
  <tr>
    <th>Start</th>
    <th>End</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contests.each do |contest| %>
  <tr>
    <td><%= contest.contest_start %></td>
    <td><%= contest.contest_end %></td>
    <td><%= link_to 'Show', contest %></td>
    <td><%= link_to 'Edit', edit_contest_path(contest) %></td>
    <td><%= link_to 'Destroy', contest, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contest', new_contest_path %>

app/views/contests/new.html.erb
<h1>New contest</h1>

<%= render 'form' %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start:</b>
  <%= @contest.contest_start %>
</p>

<p>
  <b>End:</b>
  <%= @contest.contest_end %>
</p>


<%= link_to 'Edit', edit_contest_path(@contest) %> |
<%= link_to 'Back', contests_path %>