config/routes.rb
XFactorPredictor::Application.routes.draw do
  resources :metrics

  get "contest/index"

  get "contest/new"

  get "contest/show"

  get "contest/create"

  get "contest/edit"

  get "contest/update"

  get "contest/destroy"

  resources :keywords

  resources :scores

  resources :contestants do
    resources :search_terms
  end
  
  match "get_scores/:id" => "scores#generate_scores"

  get "home/index"
  
  resources :contests
  
  match "schedule_job" => "application#schedule_job_for_12_hours"
  
  match "schedule_job_24" => "application#schedule_job_for_24_hours"
  
  match "debug" => "application#debug"
  
  match "get_leaders" => "webservice#get_leaders"
  
  match "get_leaders_legally" => "webservice#get_leaders_legally"
  
  match 'get_leaders_test' => "webservice#get_leaders_test"
  
  match 'news' => "webservice#record_news_retreival"
  
  match 'info' => "webservice#record_info_retreival"
  
  match 'twitter' => "webservice#record_twitter_retreival"
  
  match 'clear_scores' => "webservice#clear_scores"

  root :to => "home#index"

end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :contestant
  belongs_to :contest
  
  def perform
    logger.info("IMMA DO IT!")
  end
  
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  include ScoresHelper
  include ContestsHelper
  include ContestantsHelper

  # GET /scores
  # GET /scores.xml
  def index
    @scores = Score.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @scores }
    end
  end

  # GET /scores/1
  # GET /scores/1.xml
  def show
    @score = Score.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @score }
    end
  end

  # GET /scores/new
  # GET /scores/new.xml
  def new
    @score = Score.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @score }
    end
  end

  # GET /scores/1/edit
  def edit
    @score = Score.find(params[:id])
  end

  # POST /scores
  # POST /scores.xml
  def create
    @score = Score.new(params[:score])

    respond_to do |format|
      if @score.save
        format.html { redirect_to(@score, :notice => 'Score was successfully created.') }
        format.xml  { render :xml => @score, :status => :created, :location => @score }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @score.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /scores/1
  # PUT /scores/1.xml
  def update
    @score = Score.find(params[:id])

    respond_to do |format|
      if @score.update_attributes(params[:score])
        format.html { redirect_to(@score, :notice => 'Score was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @score.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.xml
  def destroy
    @score = Score.find(params[:id])
    @score.destroy

    respond_to do |format|
      format.html { redirect_to(scores_url) }
      format.xml  { head :ok }
    end
  end
  
  def generate_scores
    
    contest = is_contest_running
    
    unless contest.nil?
    
      require 'time'
      @client = TwitterSearch::Client.new('app4xfactor')
      
      contestant = Contestant.find(params[:id])  
    
      unless contestant.nil? or contestant.eliminated?

        Rails.logger.info("Getting tweets for: " + contestant.name)
        
        unless contestant.search_terms.nil?
      
          contestant.search_terms.each do |s| 

            Rails.logger.info("Searching twitter for term: "  + s.value)

            tweets = @client.query :q => s.value, :rpp => '50'
            five_mins_ago = Time.now.to_i - 6000
            count = 0
            new_tweets = []
            tweets.each do |tweet|
              tweet_time = Time.parse(tweet.created_at).to_i    
                
              if (tweet_time > five_mins_ago)
                if check_for_bad_words(tweet)
                  create_bad_score(contestant, contest)
                else
                  create_good_score(contestant, contest)
                end
              
                update_latest_score_for_contest(contestant, contest)
            
                new_tweets.push(tweet)
            
              end
            end
            Rails.logger.info("number of new tweets:" + new_tweets.size.to_s)
          end
      
          Rails.logger.info('finished polling twitter for ' + contestant.name);
        end
      end
      
      if contestant.nil?
        Rails.logger.info("Couldn't locate contesant")
      elsif contestant.eliminated?
        Rails.logger.info("Contestant with id" + contestant.id + " is eliminated, skipping")
      end
      
    else
      reset_score_for_contest(contestant)
    end
  end
  
end

app/helpers/scores_helper.rb
module ScoresHelper
  
  BAD_WORDS = ['shit','crap','useless','poo','bad','arse','awful','sucked','balls']
  
  # Loop over the bad words and return the result
  def check_for_bad_words(tweet)
    tweet_text = tweet.text
    
    BAD_WORDS.each do |w|
      if tweet_text.include? w
        return true
      end
    end
    
    return false
  end
  
  def create_bad_score(contestant, contest)
    Rails.logger.info("Creating a BAD score for " + contestant.name)
    score = Score.new
    
    score.contestant = contestant
    score.value = -1 * contestant.multiplier
    score.contest = contest
    
    score.save
  end
  
  def create_good_score(contestant, contest)
    Rails.logger.info("Creating a GOOD score for " + contestant.name)
    score = Score.new
    
    score.contestant = contestant
    score.value = 1 * contestant.multiplier
    score.contest = contest
    
    score.save
  end
end

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :contestant_id %><br />
    <%= f.text_field :contestant_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<h1>Listing scores</h1>

<table>
  <tr>
    <th>Value</th>
    <th>Contestant</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scores.each do |score| %>
  <tr>
    <td><%= score.value %></td>
    <td><%= score.contestant_id %></td>
    <td><%= link_to 'Show', score %></td>
    <td><%= link_to 'Edit', edit_score_path(score) %></td>
    <td><%= link_to 'Destroy', score, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Score', new_score_path %>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @score.value %>
</p>

<p>
  <b>Contestant:</b>
  <%= @score.contestant_id %>
</p>


<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>