config/routes.rb
XFactorPredictor::Application.routes.draw do
  resources :metrics

  get "contest/index"

  get "contest/new"

  get "contest/show"

  get "contest/create"

  get "contest/edit"

  get "contest/update"

  get "contest/destroy"

  resources :keywords

  resources :scores

  resources :contestants do
    resources :search_terms
  end
  
  match "get_scores/:id" => "scores#generate_scores"

  get "home/index"
  
  resources :contests
  
  match "schedule_job" => "application#schedule_job_for_12_hours"
  
  match "schedule_job_24" => "application#schedule_job_for_24_hours"
  
  match "debug" => "application#debug"
  
  match "get_leaders" => "webservice#get_leaders"
  
  match "get_leaders_legally" => "webservice#get_leaders_legally"
  
  match 'get_leaders_test' => "webservice#get_leaders_test"
  
  match 'news' => "webservice#record_news_retreival"
  
  match 'info' => "webservice#record_info_retreival"
  
  match 'twitter' => "webservice#record_twitter_retreival"
  
  match 'clear_scores' => "webservice#clear_scores"

  root :to => "home#index"

end

app/models/metric.rb
class Metric < ActiveRecord::Base
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  # GET /metrics
  # GET /metrics.xml
  def index
    @metrics = Metric.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @metrics }
    end
  end

  # GET /metrics/1
  # GET /metrics/1.xml
  def show
    @metric = Metric.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @metric }
    end
  end

  # GET /metrics/new
  # GET /metrics/new.xml
  def new
    @metric = Metric.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @metric }
    end
  end

  # GET /metrics/1/edit
  def edit
    @metric = Metric.find(params[:id])
  end

  # POST /metrics
  # POST /metrics.xml
  def create
    @metric = Metric.new(params[:metric])

    respond_to do |format|
      if @metric.save
        format.html { redirect_to(@metric, :notice => 'Metric was successfully created.') }
        format.xml  { render :xml => @metric, :status => :created, :location => @metric }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @metric.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /metrics/1
  # PUT /metrics/1.xml
  def update
    @metric = Metric.find(params[:id])

    respond_to do |format|
      if @metric.update_attributes(params[:metric])
        format.html { redirect_to(@metric, :notice => 'Metric was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @metric.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /metrics/1
  # DELETE /metrics/1.xml
  def destroy
    @metric = Metric.find(params[:id])
    @metric.destroy

    respond_to do |format|
      format.html { redirect_to(metrics_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/views/metrics/_form.html.erb
<%= form_for(@metric) do |f| %>
  <% if @metric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metric.errors.count, "error") %> prohibited this metric from being saved:</h2>

      <ul>
      <% @metric.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip_address %><br />
    <%= f.text_field :ip_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/metrics/edit.html.erb
<h1>Editing metric</h1>

<%= render 'form' %>

<%= link_to 'Show', @metric %> |
<%= link_to 'Back', metrics_path %>

app/views/metrics/index.html.erb
<h1>Listing metrics</h1>

<table>
  <tr>
    <th>Ip address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @metrics.each do |metric| %>
  <tr>
    <td><%= metric.ip_address %></td>
    <td><%= link_to 'Show', metric %></td>
    <td><%= link_to 'Edit', edit_metric_path(metric) %></td>
    <td><%= link_to 'Destroy', metric, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Metric', new_metric_path %>

app/views/metrics/new.html.erb
<h1>New metric</h1>

<%= render 'form' %>

<%= link_to 'Back', metrics_path %>

app/views/metrics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ip address:</b>
  <%= @metric.ip_address %>
</p>


<%= link_to 'Edit', edit_metric_path(@metric) %> |
<%= link_to 'Back', metrics_path %>